name: fitwithus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  email_validator: ^3.0.0
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env